// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZTXCSJZR-Nr6eWQQZgafLkHoJ6krMHI',
    appId: '1:1064822286663:web:c608f6785c6debff248462',
    messagingSenderId: '1064822286663',
    projectId: 'giuaki-d3236',
    authDomain: 'giuaki-d3236.firebaseapp.com',
    storageBucket: 'giuaki-d3236.firebasestorage.app',
    measurementId: 'G-CSYN814909',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnySUSQ0v5l1XUoGrLhmdOdGuiDZHbNRA',
    appId: '1:1064822286663:android:8953fd51423942d8248462',
    messagingSenderId: '1064822286663',
    projectId: 'giuaki-d3236',
    storageBucket: 'giuaki-d3236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjmb-oWiuelgWsz3WQHttanoVSc-pl8wQ',
    appId: '1:1064822286663:ios:4357afeab6afa566248462',
    messagingSenderId: '1064822286663',
    projectId: 'giuaki-d3236',
    storageBucket: 'giuaki-d3236.firebasestorage.app',
    iosBundleId: 'com.example.giuaki',
  );
}
